def intro():
    import random
    import time
    import os
    reset ='\033[0m'
    bold = '\033[1m'
    TitleYellow = "\033[33m"
    TitleCyan = "\033[36m"
    TitleMagenta = "\033[35m"
    y=int(0)
    w=int(0)
    print(bold+TitleMagenta+'Initializing. . . . . '+reset)
    time.sleep(1.0)
    space = '                    '
    while y<30:
        time.sleep(0.05)
        x=random.randint(1,10)
        if x==1:
            print('\033[31m00000000 00110001 00110011 00110011 00110000 000000000 0000000 00110001 00110011 00110011 00110000 00000000 00000000 00110001 00110011 00110011 00110000 00000000\033[0m')
        if x==2:
            print('\033[31m01110000 01111001 01110100 01101000 01101111 01101110 01110000 01111001 01110100 01101000 01101111 01101110 01110000 01111001 01110100 01101000 01101111 01101110\033[0m')
        if x==3:
            print('\033[32m00000000 01100101 01101110 01100111 01100111 00000000 00000000 01100101 01101110 01100111 01100111 00000000 00000000 01100101 01101110 01100111 01100111 00000000\033[0m')
        if x==4:
            print('\033[32m01101000 01101011 01110101 01101000 01101011 01110101 01101000 01101011 01110101 01101000 01101011 01110101 01101000 01101011 01110101 01101000 01101011 01110101\033[0m')
        if x==5:
            print('\033[33m01000001 01100111 01110010 01100001 01100100 01100101 01000001 01100111 01110010 01100001 01100100 01100101 01000001 01100111 01110010 01100001 01100100 01100101\033[0m')
        if x==6:
            print('\033[33m00000000 01100111 01110000 01100001 00110100 00000000 00000000 01100111 01110000 01100001 00110100 00000000 00000000 01100111 01110000 01100001 00110100 00000000\033[0m')
        if x==7:
            print('\033[34m00000000 01000011 01010011 01001000 01001011 01010101 00000000 01000011 01010011 01001000 01001011 01010101 00000000 01000011 01010011 01001000 01001011 01010101\033[0m')
        if x==8: 
            print('\033[34m01100101 01101110 01100111 01101001 01101110 01100101 01100101 01101110 01100111 01101001 01101110 01100101 01100101 01101110 01100111 01101001 01101110 01100101\033[0m')
        if x==9:
            print('00000000 00110001 00111001 00110001 00110011 00000000 00000000 00110001 00111001 00110001 00110011 00000000 00000000 00110001 00111001 00110001 00110011 00000000')
        if x==10:
            print('00000000 00110010 00110000 00110010 00110011 00000000 00000000 00110010 00110000 00110010 00110011 00000000 00000000 00110010 00110000 00110010 00110011 00000000')
        y+=1
    os.system('clear')
    os.system('clear')

    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`') 
    time.sleep(0.05)     
    os.system('clear') 
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    print(space+'@@@@@@^  @@    *@@    ,\@@@@/`    ,\@@@@[`      =@@@@@@^ *\@@@@[   ,@@@@/`   ,@@@@[  ')      
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print()
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    print(space+'@@@@@@^  @@    *@@    ,\@@@@/`    ,\@@@@[`      =@@@@@@^ *\@@@@[   ,@@@@/`   ,@@@@[  ')      
    print()                                                                                                
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    print(space+'@@@@@@^  @@    *@@    ,\@@@@/`    ,\@@@@[`      =@@@@@@^ *\@@@@[   ,@@@@/`   ,@@@@[  ')      
    print()                                                                                                
    print(space+'                                   ,]`     ,]     ,]` ')                                                                                                 
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    print(space+'@@@@@@^  @@    *@@    ,\@@@@/`    ,\@@@@[`      =@@@@@@^ *\@@@@[   ,@@@@/`   ,@@@@[  ')      
    print()                                                                                                
    print(space+'                                   ,]`     ,]     ,]` ')                                                                                                 
    print(space+'                                *@[=@^     =@   @/`@^  ')                                                                                             
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    print(space+'@@@@@@^  @@    *@@    ,\@@@@/`    ,\@@@@[`      =@@@@@@^ *\@@@@[   ,@@@@/`   ,@@@@[  ')      
    print()                                                                                                
    print(space+'                                   ,]`     ,]     ,]` ')                                                                                                 
    print(space+'                                *@[=@^     =@   @/`@^  ')                                                                                             
    print(space+'                                   =@^     =@      @^   ')                                                                                             
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    print(space+'@@@@@@^  @@    *@@    ,\@@@@/`    ,\@@@@[`      =@@@@@@^ *\@@@@[   ,@@@@/`   ,@@@@[  ')      
    print()                                                                                                
    print(space+'                                   ,]`     ,]     ,]` ')                                                                                                 
    print(space+'                                *@[=@^     =@   @/`@^  ')                                                                                             
    print(space+'                                   =@^     =@      @^   ')                                                                                             
    print(space+'                                   =@^     =@      @^  ')                                                                                              
    time.sleep(0.05)
    os.system('clear')
    print()
    print()
    print('@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print('@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    print(space+'@@@@@@^  @@    *@@    ,\@@@@/`    ,\@@@@[`      =@@@@@@^ *\@@@@[   ,@@@@/`   ,@@@@[  ')      
    print()                                                                                                
    print(space+'                                   ,]`     ,]     ,]` ')                                                                                                 
    print(space+'                                *@[=@^     =@   @/`@^  ')                                                                                             
    print(space+'                                   =@^     =@      @^   ')                                                                                             
    print(space+'                                   =@^     =@      @^  ')                                                                                              
    print(space+'                                   =@^     =@      @^  ')                                                                          
    time.sleep(0.05)
    os.system('clear')
    print()
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    print(space+'@@@@@@^  @@    *@@    ,\@@@@/`    ,\@@@@[`      =@@@@@@^ *\@@@@[   ,@@@@/`   ,@@@@[  ')      
    print()                                                                                                
    print(space+'                                   ,]`     ,]     ,]` ')                                                                                                 
    print(space+'                                *@[=@^     =@   @/`@^  ')                                                                                             
    print(space+'                                   =@^     =@      @^   ')                                                                                             
    print(space+'                                   =@^     =@      @^  ')                                                                                              
    print(space+'                                   =@^     =@      @^  ')                                                                          
    print(space+'                                   =@^     =@      @^  ')                                                                         
    time.sleep(0.05)
    os.system('clear')
    print(space+'@/[[[[`  @@\    =@    ]@@[[@@\   */@@[\@@^       ,/@@*   *@@/\@@*  =@@[@@^   /@/[@@`')      
    print(space+'@^       @@\@*  =@  ,@^         =@`             ** =@*        *@^       =@  =@    =@*')      
    print(space+'@\]]]]   @@ =@` =@  /@          @^                 =@*    *]]@@`    ,]/@/*  @^    *@^')      
    print(space+'@^       @@  =@`=@  =@      =@  @\      @^         =@*        ,@\       \@` @^    *@^')      
    print(space+'@^       @@   ,@@@  *@\*    =@  ,@\     @^         =@*         /@       ,@^ =@*   /@ ')      
    print(space+'@@@@@@^  @@    *@@    ,\@@@@/`    ,\@@@@[`      =@@@@@@^ *\@@@@[   ,@@@@/`   ,@@@@[  ')      
    print()                                                                                                
    print(space+'                                   ,]`     ,]     ,]` ')                                                                                                 
    print(space+'                                *@[=@^     =@   @/`@^  ')                                                                                             
    print(space+'                                   =@^     =@      @^   ')                                                                                             
    print(space+'                                   =@^     =@      @^  ')                                                                                              
    print(space+'                                   =@^     =@      @^  ')                                                                          
    print(space+'                                   =@^    %=@      @^  ')                                                                         
    print(space+'                                   =@^ %,]*/       @^ ')                                                                              
    print()
    print(space+'>>>\033[31mENGG 1330 1J1 Present: Peg Solitaire!!!!START>>>>>>>(｡◕∀◕｡)\033[0m')
    time.sleep(2.0)
    os.system('clear')
    
    print(space+TitleMagenta + "█████╗  ███████╗ ██████╗     ███████╗ ██████╗ ██╗     ██╗████████╗ █████╗ ██╗██████╗ ███████╗")
    time.sleep(0.1)
    print(space+TitleMagenta + "██╔══██╗██╔════╝██╔════╝     ██╔════╝██╔═══██╗██║     ██║╚══██╔══╝██╔══██╗██║██╔══██╗██╔════╝")
    time.sleep(0.1)
    print(space+TitleYellow + "██████╔╝█████╗  ██║  ███╗    ███████╗██║   ██║██║     ██║   ██║   ███████║██║██████╔╝█████╗  ")
    time.sleep(0.1)
    print(space+TitleCyan + "██╔═══╝ ██╔══╝  ██║   ██║    ╚════██║██║   ██║██║     ██║   ██║   ██╔══██║██║██╔══██╗██╔══╝  ")
    time.sleep(0.1)
    print(space+TitleCyan + "██║     ███████╗╚██████╔╝    ███████║╚██████╔╝███████╗██║   ██║   ██║  ██║██║██║  ██║███████╗")
    time.sleep(0.1)
    print(space+TitleCyan + "╚═╝     ╚══════╝ ╚═════╝     ╚══════╝ ╚═════╝ ╚══════╝╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚══════╝")
    print(space+'                                           \033[1;35mProduction:1J1 gaming production ltd. co.\033[0m')
    print(space+bold+TitleMagenta+'How to Play:'+reset)
    print(space+TitleCyan+'Peg solitaire is a Chinese-Checkers-style logic and strategy puzzle.'+reset)
    print(space+TitleCyan+'You are going to remove pegs by jumping over them, just like Checkers,'+reset) 
    print(space+TitleCyan+'until only one peg remains in the center of the board.'+reset)
    print(space+TitleCyan+'In our game, the dots are pegs and the circles are empty holes.'+reset)
    print(space+TitleCyan+'And the destination, which is where the last peg should be, will be shown on the right of the board.'+reset)
    time.sleep(0.75)
    print(space+TitleYellow+'1.You will first choose a map and start your game'+reset)
    print(space+TitleYellow+'2.Our program will ask you whether to play or quit'+reset)
    print(space+TitleYellow+'  Enter p to play and q to quit'+reset)
    print(space+TitleYellow+'3.Then choose a peg by entering which row an which col it is'+reset)
    print(space+TitleYellow+'  If the input is invalid, you will go back to step2 and decide whether to continue or quit'+reset)
    print(space+TitleYellow+'4.For a movable peg, control its move using wasd(w:↑,a:←,s:↓,d:→)'+reset)
    print(space+TitleYellow+'  A valid move is to jump a peg orthogonally over an adjacent peg into a hole two positions away'+reset)
    print(space+TitleYellow+'  and then to remove the jumped peg.'+reset)
    print(space+TitleYellow+'After making a valid move, go back to step2 for the next move'+reset)
    print()
    time.sleep(0.3)

                                                                                                                                                                    

                                                                                                
                                                                                                
                                                                                    
